# Generated by Django 4.1.7 on 2023-05-23 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sub Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event type')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Event')),
                ('tagline', models.CharField(max_length=50, verbose_name='Tag line of event')),
                ('schedule', models.DateTimeField(verbose_name='Schedule')),
                ('description', models.TextField(verbose_name='Description of Event')),
                ('file', models.ImageField(upload_to='Event/Files', verbose_name='Event Image')),
                ('rigor_rank', models.IntegerField(verbose_name='Rigor Rank')),
                ('attendees', models.CharField(max_length=50, verbose_name='Attendees')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.category', verbose_name='Category')),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.subcategory', verbose_name='SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
